[book]
title = "Discovery"
description = "Discover the world of microcontrollers through Rust, with STM32F429"
author = "Alex McNurlan"
language = "en"

[output.html]
additional-css = ["custom.css"]
git-repository-url = "https://github.com/rust-embedded/discovery/"
